# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('lorawan-example', ['lorawan'])
    obj.source = 'lorawan-example.cc'

    obj = bld.create_ns3_program('lorawan-example-tracing', ['lorawan', 'netanim'])
    obj.source = 'lorawan-example-tracing.cc'

    obj = bld.create_ns3_program('lorawan-phy-example', ['lorawan'])
    obj.source = 'lorawan-phy-example.cc'

    obj = bld.create_ns3_program('lorawan-unconfirmed-data-up-example', ['lorawan'])
    obj.source = 'lorawan-unconfirmed-data-up-example.cc'

    obj = bld.create_ns3_program('lorawan-simultaneous-unconfirmed-data-up-example', ['lorawan'])
    obj.source = 'lorawan-simultaneous-unconfirmed-data-up-example.cc'
